version: "2.2.3"

services:
  quarkus-service:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.native
    image: watchlist:native
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://watchlist-db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      watchlist-db:
        condition: service_healthy
    networks:
      - quarkus

  watchlist-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

networks:
  quarkus:
    driver: bridge
volumes:
  pgdata: